-- MySQL Script generated by MySQL Workbench
-- lun 18 jan 2021 18:54:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jeuderole
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jeuderole
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jeuderole` ;
USE `jeuderole` ;

-- -----------------------------------------------------
-- Table `jeuderole`.`arme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jeuderole`.`arme` (
  `idarme` INT NOT NULL,
  `str` INT NULL,
  `end` INT NULL,
  `prix` INT NULL,
  PRIMARY KEY (`idarme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jeuderole`.`montre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jeuderole`.`montre` (
  `idmonstre` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `xp` INT NULL,
  `str` INT NULL,
  `end` INT NULL,
  `wpn` INT NULL,
  `gold` INT NULL,
  `idarme` INT NULL,
  `arme_idarme` INT NOT NULL,
  PRIMARY KEY (`idmonstre`),
  CONSTRAINT `fk_montre_arme1`
    FOREIGN KEY (`arme_idarme`)
    REFERENCES `jeuderole`.`arme` (`idarme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_montre_arme1_idx` ON `jeuderole`.`montre` (`arme_idarme` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `jeuderole`.`pnj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jeuderole`.`pnj` (
  `idpnj` INT NOT NULL,
  `xp` INT NULL,
  PRIMARY KEY (`idpnj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jeuderole`.`joueur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jeuderole`.`joueur` (
  `idjoueur` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `xp` INT NULL,
  `str` INT NULL,
  `end` INT NULL,
  `wpn` INT NULL,
  `gold` INT NULL,
  PRIMARY KEY (`idjoueur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jeuderole`.`joueur_arme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jeuderole`.`joueur_arme` (
  `joueur_idjoueur` INT NOT NULL,
  `arme_idarme` INT NOT NULL,
  PRIMARY KEY (`joueur_idjoueur`, `arme_idarme`),
  CONSTRAINT `fk_joueur_has_arme_joueur`
    FOREIGN KEY (`joueur_idjoueur`)
    REFERENCES `jeuderole`.`joueur` (`idjoueur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_joueur_has_arme_arme1`
    FOREIGN KEY (`arme_idarme`)
    REFERENCES `jeuderole`.`arme` (`idarme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_joueur_has_arme_arme1_idx` ON `jeuderole`.`joueur_arme` (`arme_idarme` ASC) VISIBLE;

CREATE INDEX `fk_joueur_has_arme_joueur_idx` ON `jeuderole`.`joueur_arme` (`joueur_idjoueur` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `jeuderole`.`pnj_arme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jeuderole`.`pnj_arme` (
  `pnj_idpnj` INT NOT NULL,
  `arme_idarme` INT NOT NULL,
  PRIMARY KEY (`pnj_idpnj`, `arme_idarme`),
  CONSTRAINT `fk_pnj_has_arme_pnj1`
    FOREIGN KEY (`pnj_idpnj`)
    REFERENCES `jeuderole`.`pnj` (`idpnj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pnj_has_arme_arme1`
    FOREIGN KEY (`arme_idarme`)
    REFERENCES `jeuderole`.`arme` (`idarme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_pnj_has_arme_arme1_idx` ON `jeuderole`.`pnj_arme` (`arme_idarme` ASC) VISIBLE;

CREATE INDEX `fk_pnj_has_arme_pnj1_idx` ON `jeuderole`.`pnj_arme` (`pnj_idpnj` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
