-- MySQL Script generated by MySQL Workbench
-- jeu 21 jan 2021 16:14:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gamerole
-- -----------------------------------------------------
-- DROP SCHEMA IF EXISTS `gamerole` ;

-- -----------------------------------------------------
-- Schema gamerole
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gamerole` ;
USE `gamerole` ;

-- -----------------------------------------------------
-- Table `gamerole`.`arme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamerole`.`arme` (
  `idarme` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `str` INT NULL,
  `end` INT NULL,
  `prix` INT NULL,
  PRIMARY KEY (`idarme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gamerole`.`joueur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamerole`.`joueur` (
  `idjoueur` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `hp` INT NULL,
  `xp` INT NULL,
  `str` INT NULL,
  `end` INT NULL,
  `gold` INT NULL,
  PRIMARY KEY (`idjoueur`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idjoueur_UNIQUE` ON `gamerole`.`joueur` (`idjoueur` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gamerole`.`joueur_arme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamerole`.`joueur_arme` (
  `joueur_idjoueur` INT NOT NULL,
  `arme_idarme` INT NOT NULL,
  `equipee` TINYINT NULL,
  PRIMARY KEY (`joueur_idjoueur`, `arme_idarme`),
  CONSTRAINT `fk_joueur_has_arme_joueur`
    FOREIGN KEY (`joueur_idjoueur`)
    REFERENCES `gamerole`.`joueur` (`idjoueur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_joueur_has_arme_arme1`
    FOREIGN KEY (`arme_idarme`)
    REFERENCES `gamerole`.`arme` (`idarme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_joueur_has_arme_arme1_idx` ON `gamerole`.`joueur_arme` (`arme_idarme` ASC) VISIBLE;

CREATE INDEX `fk_joueur_has_arme_joueur_idx` ON `gamerole`.`joueur_arme` (`joueur_idjoueur` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gamerole`.`monstre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamerole`.`monstre` (
  `idmonstre` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `hp` INT NULL,
  `xp` INT NULL,
  `str` INT NULL,
  `end` INT NULL,
  `wpn` INT NULL,
  `gold` INT NULL,
  `arme_idarme` INT NOT NULL,
  PRIMARY KEY (`idmonstre`),
  CONSTRAINT `fk_montre_arme1`
    FOREIGN KEY (`arme_idarme`)
    REFERENCES `gamerole`.`arme` (`idarme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_montre_arme1_idx` ON `gamerole`.`monstre` (`arme_idarme` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gamerole`.`pnj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamerole`.`pnj` (
  `idpnj` INT NOT NULL,
  `xp` INT NULL,
  PRIMARY KEY (`idpnj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gamerole`.`pnj_arme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamerole`.`pnj_arme` (
  `pnj_idpnj` INT NOT NULL,
  `arme_idarme` INT NOT NULL,
  PRIMARY KEY (`pnj_idpnj`, `arme_idarme`),
  CONSTRAINT `fk_pnj_has_arme_pnj1`
    FOREIGN KEY (`pnj_idpnj`)
    REFERENCES `gamerole`.`pnj` (`idpnj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pnj_has_arme_arme1`
    FOREIGN KEY (`arme_idarme`)
    REFERENCES `gamerole`.`arme` (`idarme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_pnj_has_arme_arme1_idx` ON `gamerole`.`pnj_arme` (`arme_idarme` ASC) VISIBLE;

CREATE INDEX `fk_pnj_has_arme_pnj1_idx` ON `gamerole`.`pnj_arme` (`pnj_idpnj` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
